name: CrownPunishments
version: '1.3'
main: cp.corona.crownpunishments.CrownPunishments
api-version: '1.18'

commands:
  crown:
    description: Main command for CrownPunishments.
    usage: /<command> [punish|reload|help|unpunish]

  punish: # Alias command for direct /punish usage - ALIAS OF /CROWN PUNISH
    description: Alias for /crown punish command.
    usage: /<command> <player> [type] [time] [reason]

  unpunish: # Top level command for unpunishing players directly - SEPARATE TOP LEVEL COMMAND
    description: Command to directly unpunish players.
    usage: /<command> <player> <type>

  softban: # Top level command for softbanning players directly - SEPARATE TOP LEVEL COMMAND, MIRRORS /CROWN PUNISH SOFTBAN
    description: Command to directly softban players.
    usage: /<command> <player> [time] [reason]

  freeze: # Top level command for freezing players directly - SEPARATE TOP LEVEL COMMAND, MIRRORS /crown punish freeze - NEW
    description: Command to directly freeze players for manual review. # Description for /freeze command - NEW
    usage: /<command> <player> [reason] # Usage for /freeze command - NEW - Reason is now optional



permissions:
  crown.use:
    description: Allows player to use basic crown commands and punish menu
    default: op
  crown.mod:
    description: Allows player to receive frozen player messages
    default: op
  crown.admin:
    description: Allows player to use reload command
    default: op
  crown.punish.ban:
    description: Allows player to use ban related features
    default: op
  crown.unpunish.ban:
    description: Allows player to use unban related features
    default: op
  crown.punish.mute:
    description: Allows player to use mute related features
    default: op
  crown.unpunish.mute:
    description: Allows player to use unmute related features
    default: op
  crown.punish.softban:
    description: Allows player to use softban related features
    default: op
  crown.unpunish.softban:
    description: Allows player to use unsoftban related features
    default: op
  crown.punish.kick:
    description: Allows player to use kick related features
    default: op
  crown.punish.warn:
    description: Allows player to use warn related features
    default: op
  crown.punish.freeze:
    description: Allows player to use freeze related features
    default: op
  crown.unpunish.freeze:
    description: Allows player to use unfreeze related features
    default: op
  crown.bypass.softban:
    description: Allows player to bypass softbans
    default: op
  crown.bypass.freeze:
    description: Allows player to bypass freeze punishment
    default: op
  crown.bypass.ban:
    description: Allows player to bypass ban punishment
    default: op
  crown.bypass.mute:
    description: Allows player to bypass mute punishment
    default: op
  crown.bypass.warn:
    description: Allows player to bypass warn punishment
    default: op
  crown.bypass.kick:
    description: Allows player to bypass kick punishment
    default: op